// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJwH9BqfSA9uerwMrNc4aky5X90mq4qVI',
    appId: '1:809536286884:web:8d055d35fe61e50d5f3631',
    messagingSenderId: '809536286884',
    projectId: 'code2drive-flutter-project',
    authDomain: 'code2drive-flutter-project.firebaseapp.com',
    storageBucket: 'code2drive-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMBDCBr9f8WMPWVVfAvUt96VUh1m2yac',
    appId: '1:809536286884:android:9296ac2ae70aa80a5f3631',
    messagingSenderId: '809536286884',
    projectId: 'code2drive-flutter-project',
    storageBucket: 'code2drive-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATreB0V-_HODZFARB-ISsTWunRwGsN1cY',
    appId: '1:809536286884:ios:0cfe00554eb2c23d5f3631',
    messagingSenderId: '809536286884',
    projectId: 'code2drive-flutter-project',
    storageBucket: 'code2drive-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.code2drive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATreB0V-_HODZFARB-ISsTWunRwGsN1cY',
    appId: '1:809536286884:ios:0cfe00554eb2c23d5f3631',
    messagingSenderId: '809536286884',
    projectId: 'code2drive-flutter-project',
    storageBucket: 'code2drive-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.code2drive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJwH9BqfSA9uerwMrNc4aky5X90mq4qVI',
    appId: '1:809536286884:web:29a98b8caa3e966d5f3631',
    messagingSenderId: '809536286884',
    projectId: 'code2drive-flutter-project',
    authDomain: 'code2drive-flutter-project.firebaseapp.com',
    storageBucket: 'code2drive-flutter-project.firebasestorage.app',
  );
}
